### ISSUE TITLE
New Home Assistant Requirement

### ISSUE THREAD

**Issue by bschatzow** [jshufro/home_assistant_noaa_tides#19]
No 'version' key in the manifest file for custom integration 'noaa_tides'. This will not be allowed in a future version of Home Assistant. Please report this to the maintainer of 'noaa_tides'

**Comment by drfloob** [comment]
@jshufro this is fixed as of https://github.com/jshufro/home_assistant_noaa_tides/commit/ffd906b6137a8d9f62a0cd1218d5f27a55ff56ba, yes?

**Comment by jshufro** [comment]
yes!
