### ISSUE TITLE
Issue in new beta Home Assistant 2023.6.0b0

### ISSUE THREAD

**Issue by bschatzow** [jshufro/home_assistant_noaa_tides#24]
With the new beta installed I am getting the following errors:
Platform error sensor.noaa_tides - cannot import name 'json_normalize' from 'pandas.io.json' (/usr/local/lib/python3.11/site-packages/pandas/io/json/__init__.py).
Maybe related to the update of python to 3.11?

**Comment by bschatzow** [comment]
Still an issue in B5.

**Comment by C-Blais** [comment]
It would certainly appear to be an issue with the python version bump; the main release sees this same issue also.

**Comment by bschatzow** [comment]
I had another custom intergration have a problem with 2023.6 release.  It was fixed here
https://github.com/custom-components/feedparser/pull/69/files
Hopefully this will help.,

**Comment by belangp** [comment]
The noaa_coops library needs to be updated. The 0.3.2 version of it fixes the issue. However, I tried replacing it in the manifest file and HA can't compile it. I'm running HA container version.

**Comment by belangp** [comment]
Thank you @jshufro! This fixed the problem right away!

**Comment by jshufro** [comment]
> The noaa_coops library needs to be updated. The 0.3.2 version of it fixes the issue. However, I tried replacing it in the manifest file and HA can't compile it. I'm running HA container version.

There's some weirdness with the dependency tree and how it's resolved in the latest home assistant. I've left my findings here:
https://github.com/home-assistant/core/issues/93978#issuecomment-1584984049

for our purposes, 0.1.9 works.
